use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::VecDeque;
use std::env;
use std::fs::File;
use std::io::{BufRead, Error, Read};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::{Arc, Mutex};
use std::{io, thread};
use warp::http::StatusCode;
use warp::{Filter, Rejection, Reply};

const LISTEN_PORT: u16 = 47890;
const AUTH_HEADER: &str = "x-flclash-auth";

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct StartParams {
    /// Deprecated: ignored. Core path is fixed next to the helper binary.
    #[serde(default)]
    pub path: String,
    /// Named pipe path the core will dial. Must match \\.\pipe\FlClashCore_*
    pub arg: String,
}

#[derive(Debug, Serialize)]
struct StartResponse {
    /// Session token generated by helper (not client-chosen).
    token: String,
}

#[derive(Debug)]
struct AuthReject(StatusCode);

impl warp::reject::Reject for AuthReject {}

fn sha256_file(path: &str) -> Result<String, Error> {
    let mut file = File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buffer = [0; 4096];

    loop {
        let bytes_read = file.read(&mut buffer)?;
        if bytes_read == 0 {
            break;
        }
        hasher.update(&buffer[..bytes_read]);
    }

    Ok(format!("{:x}", hasher.finalize()))
}

fn helper_auth_path() -> PathBuf {
    if let Ok(custom) = env::var("FLCLASH_HELPER_AUTH_PATH") {
        return PathBuf::from(custom);
    }
    let base = env::var("PROGRAMDATA").unwrap_or_else(|_| r"C:\ProgramData".into());
    PathBuf::from(base).join("FlClash").join("helper.auth")
}

fn load_helper_auth() -> Option<String> {
    if let Ok(v) = env::var("FLCLASH_HELPER_AUTH") {
        let v = v.trim().to_string();
        if !v.is_empty() {
            return Some(v);
        }
    }
    std::fs::read_to_string(helper_auth_path())
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
}

fn check_auth(header: Option<String>) -> Result<(), StatusCode> {
    let expected = match load_helper_auth() {
        Some(v) => v,
        None => return Err(StatusCode::SERVICE_UNAVAILABLE),
    };
    match header {
        Some(got) if got == expected => Ok(()),
        _ => Err(StatusCode::UNAUTHORIZED),
    }
}

fn fixed_core_path() -> PathBuf {
    let exe = env::current_exe().unwrap_or_else(|_| PathBuf::from("FlClashHelperService.exe"));
    let dir = exe
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("."));
    dir.join("FlClashCore.exe")
}

/// Only allow FlClash UI-style named pipes: \\.\pipe\FlClashCore_<digits>
fn validate_pipe_arg(arg: &str) -> Result<(), String> {
    let arg = arg.trim();
    let prefix = r"\\.\pipe\FlClashCore_";
    if !arg.starts_with(prefix) {
        return Err("arg must be \\\\.\\pipe\\FlClashCore_<id>".into());
    }
    let suffix = &arg[prefix.len()..];
    if suffix.is_empty() || !suffix.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return Err("invalid pipe name suffix".into());
    }
    if arg.len() > 256 {
        return Err("pipe name too long".into());
    }
    Ok(())
}

fn generate_session_token() -> String {
    use rand::RngCore;
    let mut buf = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut buf);
    buf.iter().map(|b| format!("{b:02x}")).collect()
}

static LOGS: Lazy<Arc<Mutex<VecDeque<String>>>> =
    Lazy::new(|| Arc::new(Mutex::new(VecDeque::with_capacity(100))));
static PROCESS: Lazy<Arc<Mutex<Option<std::process::Child>>>> =
    Lazy::new(|| Arc::new(Mutex::new(None)));

fn start(start_params: StartParams) -> Result<StartResponse, String> {
    validate_pipe_arg(&start_params.arg)?;

    let core_path = fixed_core_path();
    let core_path_str = core_path.to_string_lossy().to_string();
    if !Path::new(&core_path_str).exists() {
        return Err(format!("core not found at {core_path_str}"));
    }

    if !cfg!(debug_assertions) {
        let sha256 = sha256_file(&core_path_str).unwrap_or_default();
        if sha256 != env!("TOKEN") {
            return Err(format!(
                "The SHA256 hash of the core is: {}. Helper only allows core hash: {}.",
                sha256,
                env!("TOKEN"),
            ));
        }
    }

    let token = generate_session_token();
    if token.len() < 32 {
        return Err("failed to generate session token".into());
    }

    stop_inner();
    let mut process = PROCESS.lock().unwrap();
    match Command::new(&core_path_str)
        .stderr(Stdio::piped())
        .arg(&start_params.arg)
        .env("FLCLASH_IPC_TOKEN", &token)
        .spawn()
    {
        Ok(child) => {
            *process = Some(child);
            if let Some(ref mut child) = *process {
                let stderr = child.stderr.take().unwrap();
                let reader = io::BufReader::new(stderr);
                thread::spawn(move || {
                    for line in reader.lines() {
                        match line {
                            Ok(output) => log_message(output),
                            Err(_) => break,
                        }
                    }
                });
            }
            Ok(StartResponse { token })
        }
        Err(e) => {
            log_message(e.to_string());
            Err(e.to_string())
        }
    }
}

fn stop_inner() {
    let mut process = PROCESS.lock().unwrap();
    if let Some(mut child) = process.take() {
        let _ = child.kill();
        let _ = child.wait();
    }
    *process = None;
}

fn stop() -> String {
    stop_inner();
    String::new()
}

fn log_message(message: String) {
    let mut log_buffer = LOGS.lock().unwrap();
    if log_buffer.len() == 100 {
        log_buffer.pop_front();
    }
    log_buffer.push_back(format!("{message}\n"));
}

fn get_logs() -> impl Reply {
    let log_buffer = LOGS.lock().unwrap();
    let value = log_buffer
        .iter()
        .cloned()
        .collect::<Vec<String>>()
        .join("\n");
    warp::reply::with_header(value, "Content-Type", "text/plain")
}

fn auth_filter() -> impl Filter<Extract = (), Error = Rejection> + Clone {
    warp::header::optional::<String>(AUTH_HEADER)
        .and_then(|header: Option<String>| async move {
            match check_auth(header) {
                Ok(()) => Ok(()),
                Err(code) => Err(warp::reject::custom(AuthReject(code))),
            }
        })
        .untuple_one()
}

async fn handle_rejection(err: Rejection) -> Result<impl Reply, std::convert::Infallible> {
    if let Some(AuthReject(code)) = err.find() {
        return Ok(warp::reply::with_status(
            code.canonical_reason().unwrap_or("error").to_string(),
            *code,
        ));
    }
    Ok(warp::reply::with_status(
        "not found".to_string(),
        StatusCode::NOT_FOUND,
    ))
}

pub async fn run_service() -> anyhow::Result<()> {
    let api_ping = warp::get()
        .and(warp::path("ping"))
        .and(auth_filter())
        .map(|| "pong");

    let api_start = warp::post()
        .and(warp::path("start"))
        .and(auth_filter())
        .and(warp::body::json())
        .map(|start_params: StartParams| match start(start_params) {
            Ok(body) => {
                let json = serde_json::to_string(&body).unwrap_or_else(|_| "{}".into());
                warp::reply::with_status(json, StatusCode::OK)
            }
            Err(msg) => warp::reply::with_status(msg, StatusCode::FORBIDDEN),
        });

    let api_stop = warp::post()
        .and(warp::path("stop"))
        .and(auth_filter())
        .map(stop);

    let api_logs = warp::get()
        .and(warp::path("logs"))
        .and(auth_filter())
        .map(get_logs);

    let routes = api_ping
        .or(api_start)
        .or(api_stop)
        .or(api_logs)
        .recover(handle_rejection);

    warp::serve(routes).run(([127, 0, 0, 1], LISTEN_PORT)).await;
    Ok(())
}
